fos_rest:
    param_fetcher_listener: force
    body_listener: true
    serializer:
        serialize_null: false
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener: 'force'
        formats:
            json: true
    format_listener:
        rules:
            - { path: '^/api(?!/doc$)', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }
