version: "3.5"
services:
    app:
        build: ./docker/php-fpm
        working_dir: /app
        volumes:
            - ./:/app

    smartconversion_nginx:
        image: nginx:latest
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        links:
            - "app:php"
